[package]
name = "seasons_lib"
version = "0.1.0"
authors = ["Owen Xie <15828145+nfusionz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.19"
strum_macros = "0.19"

