[package]
name = "fish"
version = "0.1.0"
authors = ["Darokrithia <dieltabin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.3"
<<<<<<< Updated upstream
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.48"
=======

# serde = { version = "1.0.177", features = ["derive"] }
#serde = "1.0.177"
>>>>>>> Stashed changes
